controller:
  config:
    large-client-header-buffers: 4 128k
    proxy-buffer-size: 128k    
  service:
    annotations:     
      service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: /healthz
  type: LoadBalancer  
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 512Mi
  nodeSelector:
    agentpool: system
  replicaCount: 2  
rbac:
  create: true
prometheus:
  create: true
  port: 9113
